-- 코드를 입력하세요
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, B.CREATED_DATE
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_REPLY B
ON A.BOARD_ID = B.BOARD_ID
WHERE MONTH(A.CREATED_DATE) = 10 AND YEAR(A.CREATED_DATE) = 2022
ORDER BY B.CREATED_DATE ASC, A.TITLE ASC;